cheese/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView, LogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
	path('login/', LoginView.as_view(template_name='polls/login.html', next_page='/')),
	path('logout/', LogoutView.as_view(next_page='/')),
]

polls/urls.py
from django.urls import path
from . import views


app_name = 'polls'
urlpatterns = [
	path('', view=views.index, name='index'),
	path('<int:question_id>/', views.detail, name='detail'),
	path('<int:question_id>/results/', views.results, name='results'),
	path('<int:question_id>/results/vote/', views.vote, name='vote'),
	path('question/', views.question, name='question'),
	path('question/<str:question_id>/', views.question, name='question'),
	path('create/', views.create, name='create'),
]

polls/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

import datetime


class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	owner = models.ForeignKey(User, on_delete=models.CASCADE)

	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(1)

	def __str__(self) -> str:
		return self.question_text


class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self) -> str:
		return self.choice_text


class Vote(models.Model):
	choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
	voter = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self) -> str:
		return f'{self.voter} voted for {self.choice}'

polls/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.db.models import F
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


from .models import Question, Choice, Vote


def index(request):
	if request.user.is_authenticated:
		users_questions = Question.objects.filter(owner__username = request.user.username)
		question_list = Question.objects.all()
		return render(request, 'polls/index.html', {
			'question_list': question_list,
			'user': request.user,
			'users_questions': users_questions
			})
	return HttpResponseRedirect('login')

def detail(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	choices = Choice.objects.filter(question__pk=question_id)
	if len(Vote.objects.filter(voter=request.user.id,choice__in=choices)) > 0:
		return results(request, question_id)
	return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	return render(request, 'polls/results.html', {'question': question})

@login_required
def create(request):
	return render(request, 'polls/create_question.html')

@csrf_exempt
@login_required
def vote(request, question_id):
	""" Voting on some other users behalf is possible with link http://127.0.0.1:8000/2/results/vote/?choice=7&username=bob """
	
	try:
		"""
		Method POST should be used when user inputs interacts with database.
		
		"Whenever you create a form that alters data server-side, use method="post".
		This tip isn’t specific to Django; it’s good web development practice in general."
		(https://docs.djangoproject.com/en/4.0/intro/tutorial04/#write-a-minimal-form)
		
		Following variable selected_choice is gained with choice parameter in the request.
		-> Vote could be added with just an URL (e.g. /2/results/vote/?choice=6&username=alice).
		Doesn't matter which question id is set in the URL.
		"""

		question = Question.objects.get(pk=question_id)
		# voter = User.objects.get(pk=request.user.id)
		voter = User.objects.get(username=request.GET['username'])
		choice = Choice.objects.get(pk=request.GET['choice'])

		new_vote = Vote.objects.create(choice=choice, voter=voter)

	except (KeyError, Choice.DoesNotExist):
		return render(request, 'polls/detail.html', {
			'question': question,
			'error_message': "You didn't select a choice.",
		})
	else:
		choice.votes = len(Vote.objects.filter(choice=choice))
		choice.save()
		return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

@csrf_exempt
def question(request, question_id=-1):
	if request.method == 'POST':
		question = request.POST.get('questionField')
		username = request.POST.get('username')

		Question.objects.create(
			owner=User.objects.get(username=username),
			question_text=question,
			pub_date=timezone.now()
		)

		choices = []
		for key, value in request.POST.items():
			if key[:12] == 'choiceField-':
				choices.append(value)

		for choice in choices:
			Choice.objects.create(
				question=Question.objects.get(question_text=question),
				choice_text=choice
			)
		
		# query = "INSERT INTO polls_question (question_text, pub_date) " \
			# "VALUES ('" + question + "', '" + str(timezone.now()) + "');"
		# new_question = Question.objects.raw(query)

		return redirect('/')

	if request.method == 'GET':
		"""
		Flaw #2: SQL Injection.
		Adding query directly with raw-method and insecure way of adding user input in query.

		Question ID is extracted from URL parameter and injected directly to query.
		Following URL prints admin users password hash on the screen:
		http://127.0.0.1:8000/question/2%20AND%201%3D2%20UNION%20SELECT%20username,%20password,%20id,%20is_superuser%20FROM%20auth_user%20WHERE%20is_superuser%3D1/
		"""
		questions = Question.objects.raw("SELECT id, question_text, pub_date FROM polls_question;")
		if question_id != -1:
			query = f"SELECT * FROM polls_question WHERE id={question_id};"
			questions = Question.objects.raw(query)

		# questions = Question.objects.all()
		# if question_id != -1:
			# questions = Question.objects.get(id=question_id)

		return render(request, 'polls/index.html', {'users_questions': questions})
	
	return HttpResponse('Nothing was found/added')

polls/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cheese polls</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/milligram/1.4.1/milligram.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
</head>
<body>
    <nav>
        <div class="container">
            <a class="logo" href="{% url 'polls:index' %}">🧀</a>
            <ul class="navigation-list float-right">
                {% if user.is_authenticated %}
                <li><span>Hi {{ user.username }}!</span></li>
                {% endif %}
                <li><a class="button" href="{% url 'polls:create' %}">Create poll</a></li>
                <li><a class="button" href="{% url 'polls:index' %}">Home</a></li>
                {% if user.is_authenticated %}
                <li><a class="button" href="/logout">Logout</a></li>
                {% else %}
                <li><a class="button" href="/login">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <footer class="footer">
        <div class="container">
                <p><em>It's called Cheese, not because it's about cheese.<br/>
                    It's called Cheese because of the holes!</em></p>
            <span>Copyright<!-- --> © <!-- -->2022<!-- --> <a class="Link" href="https://github.com/tuukkalai" rel="noopener" target="_blank">Tuukka Laitinen</a>.</span>
        </div>
    </footer>

    {% block javascript %}{% endblock %}
</body>
</html>

polls/templates/polls/create_question.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'polls:question' %}" method="POST">
    {# {% csrf_token %} #}
    <fieldset>
        <label for="questionField">Question</label>
        <input
            type="text"
            id="questionField"
            name="questionField"
            placeholder="Where are we going?"
        />
        <input
            type="hidden"
            name="username"
            value="{{ user.username|default:'not logged in' }}"
        \>
        <div id="choices">
            <label for="choiceField-1">Choices</label>

            <input
                type="text"
                class="choiceField"
                id="choiceField-1"
                name="choiceField-1"
                placeholder="42"
                required="required"
            />

        </div>
    <button id="newChoice">+ Add another choice</button>
    <br />
    <input
        type="submit"
        class="button-primary"
        value="Create question"
    />
    </fieldset>
</form>
{% endblock %}
{% block javascript %}
<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function() {
        let addChoiceBtn = document.getElementById('newChoice');
        let numberOfChoices = document.querySelectorAll('.choiceField').length;
        addChoiceBtn.addEventListener('click', function(e) {
            e.preventDefault();
            numberOfChoices += 1;
            let newInput = document.createElement('input');
            newInput.setAttribute('type', 'text');
            newInput.setAttribute('id', `choiceField-${numberOfChoices}`);
            newInput.setAttribute('name', `choiceField-${numberOfChoices}`);
            newInput.setAttribute('required', 'required');
            document.getElementById('choices').appendChild(newInput);
        });
    });
</script>
{% endblock %}

polls/templates/polls/detail.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'polls:vote' question.id %}" method="GET">
    {# {% csrf_token %} #}
    <h1>{{ question }}</h1>
    {% for choice in question.choice_set.all %}
    <input type="radio" id="{{ choice.id }}" value="{{ choice.id }}" name="choice" />
    <label class="label-inline" for="{{ choice.id }}">{{ choice.choice_text }}</label>
    <br />
    {% endfor %}
    <input type="hidden" name="username" value="{{ user.username }}">
    <input type="submit" value="Vote" />
</form>
{% endblock %}

polls/templates/polls/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Polls app</h1>
<p>Select poll from the listing and vote.</p>

<h2>All polls</h2>
{% if question_list %}
<ul>
{% for question in question_list %}
    {#<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>#}
    <li><a href="/{{ question.id }}">{{ question.question_text }}</a></li>
{% endfor %}
</ul>
{% endif %}

<h2>My polls</h2>
{% if users_questions %}
<ul>
{% for question in users_questions %}
    {#<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>#}
    <li><a href="/{{ question.id }}">{{ question.question_text }}</a></li>
{% endfor %}
</ul>
{% else %}
<p>No polls available.</p>
{% endif %}

{% endblock %}

polls/templates/polls/login.html
{% extends 'base.html' %}

{% block content %}
<h2>Login</h2>
<form method="post">
    <fieldset>
        {% csrf_token %}
        {{ form.as_p }}
        <input class="button-primary" type="submit" value="Login" />
    </fieldset>
</form>
{% endblock %}

polls/templates/polls/results.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ question.question_text }}</h1>
{% if question.choice_set.count > 0 %}
<table>
    <thead>
        <tr>
            <th>Question</th>
            <th># of votes</th>
        </tr>
    </thead>
    <tbody>
    {% for choice in question.choice_set.all %}
        <tr>
            <td>{{ choice.choice_text }}</td>
            <td>{{ choice.votes }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<p>No choices for this question</p>
{% endif %}
{% endblock %}